### ISSUE TITLE
Transpilation approach

### ISSUE THREAD

**Issue by echeran** [unicode-org/omnicu#1]
One approach to accomplish the main goals in the OmnICU Charter is to have a transpiler that converts input source code into the equivalent source code for each target language (or platform).

The intent of this approach is to decouple the code deliverable from the target language toolchain and allow the toolchain to optimize code on a per-application basis.  The result would allow the target code to run with minimal dependencies and code size.

The input source code should represent the i18n functionality that is in the scope for OmnICU.  It should also be able to pass unit tests that check the logical correctness of the input code itself, and do so before any transpilation occurs.  This ensures an authoritative source of truth for logical correctness tests, decoupled from target language/runtime effects.

**Comment by sffc** [comment]
Is there anything more about the Transpilation Approach that needs to be documented?  If not, please close the issue.

**Comment by sffc** [comment]
I'm going to close this issue as fixed by #9.
