### ISSUE TITLE
Crate Namespace

### ISSUE THREAD

**Issue by sffc** [unicode-org/omnicu#16]
How do we name our crates?  This depends a bit on the answer to #13, but we have two general options:

1. Prefix the names with "icu"
2. Prefix the names with "omnicu"

@zbraniecki had some arguments for preferring "icu".  Can you lay those out here?

**Comment by sffc** [comment]
Should probably go in the Rust Style Guide (#12).

Now that we're called "icu4x", it might be easier to justify using "icu" as the crate namespace.

Do we need to reserve any key names?

Reassigning to Manish who has more knowledge of the Rust ecosystem.

**Comment by Manishearth** [comment]
I think `icu` is fine. `icu4x-foo` feels cumbersome.

I would reserve `icu`, and `ico-foo` for all "foo" in things like "datetime", "plural", "number", etc (idk if we should call it number or numberformat)

I've proposed optional namespacing for crates.io before so that we can just reserve `icu` and get `icu/foo` for free.

**Comment by zbraniecki** [comment]
Proposal based on the [ecosystem](https://github.com/unicode-org/omnicu/blob/master/docs/ecosystem.md):

* `icu`
* `icu4x`
* `*-datetime`
* `*-locale`
* `*-bidi`
* `*-normalization`
* `*-script`
* `*-idna`
* `*-pluralrules`
* `*-breakiterator`
* `*-collator`
* `*-number`

**Comment by Manishearth** [comment]
makes sense to me

**Comment by sffc** [comment]
We haven't discussed this yet, because I'm in part waiting for a conclusion from the licensing thread, but I'm not convinced that all 10 crates in ecosystem.md should necessarily be upstreamed.  I think some of them, particularly those that are tangential to 402, may be best left as their own crates in their own repositories with their own names.

So, for the time being, I would reserve:

- `icu`
- `icu4x`
- `icu-locale`
- `icu-langid`

But, for reasons Manish mentioned (reserving crate names can muddy search results if we don't end up using them), I think it's premature to reserve crate names for all those other components.

**Comment by zbraniecki** [comment]
ok! Reserving three crate names then:

* icu
* icu4x
* icu-locale

I'm leaning toward a single crate with two structs `LanguageIdentifier` and `Locale`, so I'll start with that and we can add `icu-langid` if needed.

**Comment by nciric** [comment]
That sounds great.
