### ISSUE TITLE
Document intent for regular expressions

### ISSUE THREAD

**Issue by hsivonen** [unicode-org/omnicu#37]
[ecosystem.md](https://github.com/unicode-org/omnicu/blob/master/docs/ecosystem.md) mentions `icu::Regex`. The Rust [`regex` crate](https://crates.io/crates/regex) already exists and is very performant (in part due to not supporting some Perl-popularized features that aren't actually regular and hinder performance).

It might be useful to signal intent in this area at some point.

Does the project seek to provide regular expressions that operate on UTF-8 for Rust apps? If so, what would be the elevator pitch relative to the `regex` crate?

Does the project seek to provide regular expressions that operate on UTF-16 and Latin1 and conform to ECMAScript regular expressions for use in JavaScript engines? If so, what would be the elevator pitch relative to what SpiderMonkey and V8 already have?

Does the project seek to provide regular expressions that Dart or Go programs would use? If so, what would be the elevator pitch relative to what the standard libraries of these languages provide?

Does the project seek to provide regular expressions that C or C++ apps would use via FFI? If so, would this just FFI around the `regex` crate (i.e. UTF-8), something new, or for UTF-16?

**Comment by zbraniecki** [comment]
Is there any performance/memory benchmark that takes `regex` against `irrexep` or other popular reggexp engines?

**Comment by nciric** [comment]
I think there are two potential reasons for developing icu4x regex:

1. Full Unicode support (script ranges for example)
2. Potential for easy Wasm compilation

Now, I don't know if Rust regex crate already offers this. If so, we could
just fallback to it, without developing our own, if licencing is not a
problem.

пет, 17. апр 2020. у 01:33 Zibi Braniecki <notifications@github.com> је
написао/ла:

**Comment by zbraniecki** [comment]
> if licencing is not a problem.

According to the latest I saw, it shouldn't be!

https://github.com/rust-lang/regex#license

**Comment by nciric** [comment]
It seems it supports some level of Unicode algo -
https://github.com/rust-lang/regex/blob/master/UNICODE.md

Which brings another question - what to do with Unicode properties. Can
they be shared across crates?

пет, 17. апр 2020. у 10:32 Zibi Braniecki <notifications@github.com> је
написао/ла:

**Comment by macchiati** [comment]
I just looked over the description on
https://github.com/rust-lang/regex/blob/master/UNICODE.md. The support is,
in general, quite good.

The main area where it falls down is in support of more Unicode properties.
A second question I have is how good Rust is about updating to the newest
version of Unicode, and whether there is an API in Rust to detect the
version of Unicode supported.

Mark

**Comment by sffc** [comment]
I'll take this issue and add a note about this to ecosystem.md.  I plan to send a PR to that doc with a new column saying to what degree we want to pull in existing code from each crate.

**Comment by sffc** [comment]
I added this to #41 and am documenting that we don't intend to take action on regex support in ICU4X at this time.
